"""Add requests map data

Revision ID: 3402fc388e1d
Revises: 90b4fce7b615
Create Date: 2024-05-13 14:54:12.015931

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3402fc388e1d'
down_revision = '90b4fce7b615'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_requests',
    sa.Column('req_id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('message_id', sa.BigInteger(), nullable=True),
    sa.Column('sent', sa.Boolean(), nullable=True),
    sa.Column('sent_message_id', sa.BigInteger(), nullable=True),
    sa.PrimaryKeyConstraint('req_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_requests')
    # ### end Alembic commands ###