"""chat cascade delete

Revision ID: 501575df3195
Revises: d7d90c27ce0f
Create Date: 2024-05-14 11:17:42.876997

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '501575df3195'
down_revision = 'd7d90c27ce0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('chat_version_aware', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=False)
    op.drop_constraint('chat_version_aware_chat_id_fkey', 'chat_version_aware', type_='foreignkey')
    op.create_foreign_key(None, 'chat_version_aware', 'chats', ['chat_id'], ['chat_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('request_texts_chat_id_fkey', 'request_texts', type_='foreignkey')
    op.create_foreign_key(None, 'request_texts', 'chats', ['chat_id'], ['chat_id'], onupdate='CASCADE', ondelete='CASCADE')
    op.drop_constraint('user_requests_chat_id_fkey', 'user_requests', type_='foreignkey')
    op.create_foreign_key(None, 'user_requests', 'chats', ['chat_id'], ['chat_id'], onupdate='CASCADE', ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_requests', type_='foreignkey')
    op.create_foreign_key('user_requests_chat_id_fkey', 'user_requests', 'chats', ['chat_id'], ['chat_id'], onupdate='CASCADE')
    op.drop_constraint(None, 'request_texts', type_='foreignkey')
    op.create_foreign_key('request_texts_chat_id_fkey', 'request_texts', 'chats', ['chat_id'], ['chat_id'], onupdate='CASCADE')
    op.drop_constraint(None, 'chat_version_aware', type_='foreignkey')
    op.create_foreign_key('chat_version_aware_chat_id_fkey', 'chat_version_aware', 'chats', ['chat_id'], ['chat_id'], onupdate='CASCADE')
    op.alter_column('chat_version_aware', 'chat_id',
               existing_type=sa.BIGINT(),
               nullable=True)
    # ### end Alembic commands ###