"""02. Create chats

Revision ID: 526031485840
Revises: 4d1aac6576f4
Create Date: 2023-03-01 23:38:40.903106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526031485840'
down_revision = '4d1aac6576f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chats',
                    sa.Column('chat_id', sa.INTEGER(), autoincrement=True, nullable=False),
                    sa.Column('show_intro', sa.BOOLEAN(), autoincrement=False, nullable=True),
                    sa.PrimaryKeyConstraint('chat_id', name='chats_pkey')
                    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chats')
    # ### end Alembic commands ###
