"""chat primary key, add release notes

Revision ID: 5d3779d5f5cf
Revises: 3402fc388e1d
Create Date: 2024-05-13 21:07:35.636285

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '5d3779d5f5cf'
down_revision = '3402fc388e1d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('release_notes',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('version', sa.String(), nullable=False),
                    sa.Column('notes', sa.String(), nullable=False),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.create_table('chat_version_aware',
                    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
                    sa.Column('chat_id', sa.BigInteger(), nullable=True),
                    sa.Column('version', sa.String(), nullable=False),
                    sa.ForeignKeyConstraint(['chat_id'], ['chats.chat_id'], onupdate='CASCADE'),
                    sa.PrimaryKeyConstraint('id')
                    )

    op.add_column('chats', sa.Column('id', sa.BigInteger(),
                                     autoincrement=True, primary_key=True, nullable=False))

    op.create_index(op.f('ix_chats_chat_id'), 'chats', ['chat_id'], unique=False)
# ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_chats_chat_id'), table_name='chats')
    op.drop_column('chats', 'id')

    op.drop_table('chat_version_aware')
    op.drop_table('release_notes')
    # ### end Alembic commands ###
