"""replace prkey in requests users and text

Revision ID: d7d90c27ce0f
Revises: b508c4bb9561
Create Date: 2024-05-14 10:57:09.272813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d90c27ce0f'
down_revision = 'b508c4bb9561'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'request_texts', 'chats', ['chat_id'], ['chat_id'], onupdate='CASCADE')
    op.create_foreign_key(None, 'user_requests', 'chats', ['chat_id'], ['chat_id'], onupdate='CASCADE')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_requests', type_='foreignkey')
    op.drop_constraint(None, 'request_texts', type_='foreignkey')
    # ### end Alembic commands ###